export const flexContainer: string;
export const end: string;
export const start: string;
export const spaceEven: string;
export const spaceBetween: string;
export const spaceAround: string;
export const center: string;
export const row: string;
export const col: string;